server:
  port: 8082

spring:
  application:
    name: safety-risk-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Gana@9380
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      export:
        enabled: false

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"