apiVersion: v1
kind: ConfigMap
metadata:
  name: safety-risk-config
  namespace: default
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
