ALTER TABLE safety_events ADD COLUMN IF NOT EXISTS action VARCHAR(32);
ALTER TABLE safety_events ADD COLUMN IF NOT EXISTS severity VARCHAR(32);
ALTER TABLE safety_events ADD COLUMN IF NOT EXISTS category VARCHAR(64);
ALTER TABLE safety_events ADD COLUMN IF NOT EXISTS session_id VARCHAR(64);
ALTER TABLE safety_events ADD COLUMN IF NOT EXISTS reason TEXT;